import {useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import {Search,Sparkles,ArrowUpRight,Send,X,ArrowRight,CheckCircle2,AlertCircle} from "lucide-react";
import {useApp} from "../context";
import {api,errorText} from "../api";
import {NAV} from "./Shell";
import {Button,Modal,Badge} from "./ui";
type Reply={answer:string;items:string[];action:string|null};
export function CommandPalette(){const {palette,setPalette,setAssistant,can}=useApp();const [q,setQ]=useState(""),[index,setIndex]=useState(0),[results,setResults]=useState<{entity:string;id:number;label:string;detail:string}[]>([]);const navigate=useNavigate();
 useEffect(()=>{if(palette){setQ("");setIndex(0);}},[palette]);
 useEffect(()=>{setIndex(0);let cancelled=false;const timer=setTimeout(()=>{if(q.trim())void api.get("/search",{params:{q}}).then(r=>{if(!cancelled)setResults(r.data);}).catch(()=>setResults([]));else setResults([]);},200);return()=>{cancelled=true;clearTimeout(timer);};},[q]);
 if(!palette)return null;
 const examples=["Why is CS302 in conflict?","Which room has capacity for 45 students?","Who has the heaviest faculty workload?"];
 const entries=[...(q?[{label:`Ask NEXUS: ${q}`,detail:"Grounded in your workspace",action:()=>setAssistant({query:q})}]:examples.map(label=>({label,detail:"Ask NEXUS",action:()=>setAssistant({query:label})}))),...results.map(r=>({label:r.label,detail:r.detail,action:()=>navigate(`/${r.entity}?search=${encodeURIComponent(r.detail)}`)})),...NAV.filter(n=>(!n.roles||can(...n.roles))&&n.label.toLowerCase().includes(q.toLowerCase())).map(n=>({label:n.label,detail:"Navigate",action:()=>navigate(`/${n.path}`)}))];
 function select(i:number){entries[i]?.action();setPalette(false);}
 return <Modal title="NEXUS Command" onClose={()=>setPalette(false)} wide><div className="palette-input"><Search size={20}/><input aria-label="Search or ask NEXUS" autoFocus placeholder="Search people, rooms, modules or ask NEXUS…" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setIndex(i=>(i+1)%entries.length);}if(e.key==="ArrowUp"){e.preventDefault();setIndex(i=>(i-1+entries.length)%entries.length);}if(e.key==="Enter")select(index);}}/></div><div className="palette-results">{entries.map((x,i)=><button key={`${x.label}-${i}`} className={index===i?"selected":""} onMouseEnter={()=>setIndex(i)} onClick={()=>select(i)}><Sparkles size={16}/><span>{x.label}<small>{x.detail}</small></span><ArrowUpRight size={16}/></button>)}</div><div className="palette-footer">↑↓ Navigate <span>↵ Select</span><span>Esc Close</span></div></Modal>;
}
export function Assistant(){const {assistant,setAssistant}=useApp(),navigate=useNavigate();const [input,setInput]=useState(""),[busy,setBusy]=useState(false),[messages,setMessages]=useState<{question:string;reply:Reply}[]>([]);const [error,setError]=useState("");
 async function ask(query:string){if(!query.trim())return;setBusy(true);setError("");setInput("");try{const {data}=await api.post<Reply>("/assistant",{query,context:assistant||{}});setMessages(m=>[...m,{question:query,reply:data}]);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 useEffect(()=>{setMessages([]);setError("");if(assistant?.query)void ask(String(assistant.query));},[assistant]);
 if(!assistant)return null;
 return <Modal title="NEXUS Assistant" onClose={()=>setAssistant(null)}><div className="assistant-body"><div className="assistant-context"><Sparkles size={17}/><div>Context active<strong>{String(assistant.label||"Academic workspace")}</strong></div><Badge>DEMO</Badge></div><p className="muted">Ask about the timetable, room availability, workload, or a recorded change.</p><div className="messages" aria-live="polite">{messages.map((m,i)=><div key={i}><div className="question">{m.question}</div><div className="answer"><Sparkles size={16}/><p>{m.reply.answer}</p>{m.reply.items.length>0&&<ul>{m.reply.items.map((x,i)=><li key={i}>{x}</li>)}</ul>}{m.reply.action&&<Button onClick={()=>{navigate(`/${m.reply.action}`);setAssistant(null);}}>Review alternatives<ArrowRight size={14}/></Button>}</div></div>)}</div>{!messages.length&&<div className="suggestions">{[assistant.session_id?"What is the safest alternative?":"Which room has capacity for 45 students?","Who has the heaviest faculty workload?","Find a free lab Thursday at 2"].map(q=><button key={q} disabled={busy} onClick={()=>void ask(q)}>{q}<ArrowUpRight size={14}/></button>)}</div>}{busy&&<p role="status">Checking workspace records…</p>}{error&&<p className="error-text" role="alert">{error}</p>}<form className="assistant-input" onSubmit={e=>{e.preventDefault();void ask(input);}}><input aria-label="Ask NEXUS" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about your academic operations…"/><Button variant="primary" aria-label="Send question" disabled={busy||!input.trim()}><Send size={17}/></Button></form><small className="muted">Structured database assistant · Changes always require review.</small></div></Modal>;
}
export function Toaster(){const {toasts,dismiss}=useApp();return <div className="toaster" aria-live="polite">{toasts.map(t=><div className={`toast ${t.tone}`} key={t.id}>{t.tone==="error"?<AlertCircle size={19}/>:<CheckCircle2 size={19}/>}<span>{t.text}</span><button aria-label="Dismiss notification" onClick={()=>dismiss(t.id)}><X size={15}/></button></div>)}</div>;}
