import {useEffect,useRef,type ReactNode,type ButtonHTMLAttributes} from "react";
import {X,Sparkles,CheckCircle2,AlertCircle,ArrowRight} from "lucide-react";
import {useApp} from "../context";
export function Button({children,variant="secondary",className="",...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:string}){return <button className={`btn ${variant} ${className}`} {...props}>{children}</button>;}
export function Badge({children,tone="neutral"}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
export function Panel({children,className=""}:{children:ReactNode;className?:string}){return <section className={`panel ${className}`}>{children}</section>;}
export function PageHeader({eyebrow="ACADEMIC OPERATIONS",title,subtitle,actions}:{eyebrow?:string;title:string;subtitle:string;actions?:ReactNode}){return <header className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div><div className="actions">{actions}</div></header>;}
export function Meter({value,tone="navy"}:{value:number;tone?:string}){return <div className={`meter ${tone}`}><span style={{width:`${Math.min(100,Math.max(0,value))}%`}}/></div>;}
export function Empty({title,description}:{title:string;description?:string}){return <div className="empty"><CheckCircle2 size={28}/><h3>{title}</h3><p>{description}</p></div>;}
export function ErrorNotice({message}:{message:string}){return <div className="notice error" role="alert"><AlertCircle size={18}/>{message}</div>;}
export function AskNexus({context={},label="Ask NEXUS"}:{context?:Record<string,unknown>;label?:string}){const {setAssistant}=useApp();return <button className="ask-link" onClick={()=>setAssistant(context)}><Sparkles size={14}/>{label}<ArrowRight size={13}/></button>;}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null),closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const root=ref.current;const focus=()=>Array.from(root?.querySelectorAll<HTMLElement>("button:not([disabled]), input:not([disabled]), select, textarea, a[href], [tabindex='0']")||[]);focus()[0]?.focus();const key=(e:KeyboardEvent)=>{const dialogs=document.querySelectorAll('[role="dialog"]');if(dialogs[dialogs.length-1]!==root)return;if(e.key==="Escape")closeRef.current();if(e.key==="Tab"){const nodes=focus(),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previous?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} className={`modal ${wide?"wide":""}`} role="dialog" aria-modal="true" aria-label={title}><div className="modal-header"><h2>{title}</h2><Button aria-label="Close dialog" variant="ghost" onClick={onClose}><X size={18}/></Button></div>{children}</div></div>;
}
