import {useEffect,useState} from "react";
import {Plus,Sparkles,Users} from "lucide-react";
import {useApp} from "../context";
import {api,errorText} from "../api";
import {PageHeader,Panel,Badge,Meter,Modal,Button,Empty,ErrorNotice} from "../components/ui";
import {time,type RecordData} from "../types";

type Exam=RecordData&{module_id:number;room_id:number;invigilator_id:number;date:string;start:number;duration:number;students:number;capacity:number;conflicts:string[]};
type Plan={proposed:{module_id:number;room_id:number;date:string;start:number}[];unscheduled:number[]};
type Venues={changes:{id:number;before:number;after:number}[];unresolved:number[]};
export default function Examinations(){
 const {workspace:w,refresh,notify}=useApp();
 const [rows,setRows]=useState<Exam[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[mode,setMode]=useState<"edit"|"plan"|"venues"|null>(null),[selected,setSelected]=useState<Exam|null>(null),[plan,setPlan]=useState<Plan|null>(null),[venues,setVenues]=useState<Venues|null>(null),[reason,setReason]=useState("");
 const [moduleId,setModuleId]=useState(0),[roomId,setRoomId]=useState(0),[facultyId,setFacultyId]=useState(0),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[start,setStart]=useState(8),[duration,setDuration]=useState(2),[days,setDays]=useState(10),[modules,setModules]=useState<number[]>([]),[seatExam,setSeatExam]=useState<number|null>(null);
 async function load(){try{setRows((await api.get<Exam[]>("/exams")).data);}catch(e){setError(errorText(e));}}
 useEffect(()=>{void load();},[]);
 if(!w)return null;
 const dates=[...new Set(rows.map(r=>r.date))].sort(),usedRooms=w.rooms.filter(r=>rows.some(e=>e.room_id===r.id)),seat=rows.find(r=>r.id===seatExam)||rows[0];
 function openEdit(exam:Exam|null){setSelected(exam);setModuleId(exam?.module_id||w!.modules[0]?.id||0);setRoomId(exam?.room_id||w!.rooms[0]?.id||0);setFacultyId(exam?.invigilator_id||w!.faculty[0]?.id||0);setDate(exam?.date||new Date().toISOString().slice(0,10));setStart(exam?.start||8);setDuration(exam?.duration||2);setReason("");setError("");setMode("edit");}
 async function save(confirm=false){
  setBusy(true);setError("");try{
   if(mode==="edit"){
    const body={module_id:moduleId,room_id:roomId,invigilator_id:facultyId,date,start,duration,reason,revision:w!.revision};
    if(selected)await api.put(`/exams/${selected.id}`,body);else await api.post("/exams",body);
   }else if(mode==="plan"){
    const {data}=await api.post<Plan>("/exams/plan",{module_ids:modules,start_date:date,days,duration,reason,revision:w!.revision,confirm});setPlan(data);if(!confirm)return;
   }else{
    const {data}=await api.post<Venues>("/exams/venues",{reason,revision:w!.revision,confirm});setVenues(data);if(!confirm)return;
   }
   await load();await refresh();setMode(null);notify("Exam allocations saved and audited.");
  }catch(e){setError(errorText(e));}finally{setBusy(false);}
 }
 return <div className="recorded-exams"><PageHeader eyebrow="OPERATE · EXAMINATIONS" title="Exam Command Center" subtitle="Plan venues, seating and invigilation for the assessment period." actions={<><Button variant="primary" onClick={()=>{setMode("plan");setPlan(null);setReason("");setModules([]);setError("");}}><Sparkles size={15}/>Generate Exam Plan</Button><Button disabled={!rows.length} onClick={()=>{setMode("venues");setVenues(null);setReason("");setError("");}}>Optimize Venues</Button></>}/>
 {error&&!mode&&<ErrorNotice message={error}/>}
 <div className="recorded-kpis five">{[["Seat demand",rows.reduce((a,r)=>a+r.students,0)],["Exams",rows.length],["Rooms",usedRooms.length],["Invigilators",new Set(rows.map(r=>r.invigilator_id)).size],["Exams with conflicts",rows.filter(r=>r.conflicts.length).length]].map(([label,value])=><Panel key={label}><span className="eyebrow">{label}</span><strong>{value}</strong></Panel>)}</div>
 <Panel><div className="section-heading"><div><h2>Assessment Timeline</h2><p>06:30–17:00 · select an exam to edit its allocation</p></div><Button onClick={()=>openEdit(null)}><Plus size={14}/>Add exam</Button></div>
 {!rows.length?<Empty title="Plan your first examination period" description="Generate a plan from selected modules, or add an exam with a confirmed date, venue and invigilator."/>:<div className="exam-timeline"><div className="exam-hours"><span/>{Array.from({length:8},(_,i)=><span key={i}>{time(6.5+i*1.5)}</span>)}</div>{dates.map(d=>{const entries=rows.filter(r=>r.date===d).sort((a,b)=>a.start-b.start),tracks:Exam[][]=[];const placements=entries.map(r=>{let track=tracks.findIndex(t=>t.every(x=>r.start>=x.start+x.duration||r.start+r.duration<=x.start));if(track<0){track=tracks.length;tracks.push([]);}tracks[track].push(r);return {r,track};});return <div className="exam-date-row" key={d}><div><strong>{new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'})}</strong><span>{entries.length} exams</span></div><div className="exam-date-lanes" style={{height:tracks.length*78+16}}>{placements.map(({r,track})=><button key={r.id} className={'exam-allocation '+(r.conflicts.length?'conflicted':r.students/r.capacity>.85?'tight':'comfortable')} style={{left:`${(r.start-6.5)/10.5*100}%`,width:`calc(${r.duration/10.5*100}% - 5px)`,top:track*78+8}} onClick={()=>openEdit(r)}><code>{String(r.code)} <small>{r.students}/{r.capacity}</small></code><strong>{String(r.module)}</strong><span>{String(r.room)} · {time(r.start)}</span></button>)}</div></div>;})}</div>}
 </Panel>
 <div className="exam-resources"><Panel><div className="section-heading"><h2>Venue & Seat Utilization</h2><Badge>{usedRooms.length} exam rooms</Badge></div>{usedRooms.map(room=>{const demand=Math.max(...rows.filter(r=>r.room_id===room.id).map(r=>r.students));return <div className="venue-row" key={room.id}><div><strong>{room.name}</strong><span>{demand}/{room.capacity} peak seats</span></div><Meter value={demand/room.capacity*100} tone={demand>room.capacity?'maroon':'teal'}/></div>;})}{seat&&<div className="seat-preview"><label>Seat demand preview<select value={seat.id} onChange={e=>setSeatExam(Number(e.target.value))}>{rows.map(r=><option value={r.id} key={r.id}>{String(r.code)} · {String(r.room)}</option>)}</select></label><div className="seat-grid" aria-label={`${seat.students} requested seats, capacity ${seat.capacity}`}>{Array.from({length:seat.capacity},(_,i)=><i title={`Seat ${i+1}${i<seat.students?' · required':''}`} key={i} className={i<seat.students?'occupied':''}/>)}</div><p className="fine-print">Capacity preview; student-to-seat assignments have not been made.</p></div>}</Panel><Panel><div className="section-heading"><h2><Users size={16}/> Invigilator Load</h2></div>{w.faculty.filter(f=>rows.some(r=>r.invigilator_id===f.id)).map(f=><div className="invigilator-row" key={f.id}><span className="avatar neutral">{f.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><strong>{f.name}</strong><Badge>{rows.filter(r=>r.invigilator_id===f.id).length} exams</Badge></div>)}<p className="panel-note">Plans check seats, availability, exam overlaps and recurring teaching commitments.</p></Panel></div>
 {mode&&<Modal wide title={mode==='edit'?(selected?'Edit examination':'Add examination'):mode==='plan'?'Generate Exam Plan':'Optimize Exam Venues'} onClose={()=>!busy&&setMode(null)}><form className="modal-body" onSubmit={e=>{e.preventDefault();void save();}}>
 {mode==='edit'?<div className="form-grid"><label>Module<select value={moduleId} onChange={e=>setModuleId(Number(e.target.value))}>{w.modules.map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select></label><label>Venue<select value={roomId} onChange={e=>setRoomId(Number(e.target.value))}>{w.rooms.filter(r=>r.active).map(r=><option key={r.id} value={r.id}>{r.name} · {r.capacity} seats</option>)}</select></label><label>Invigilator<select value={facultyId} onChange={e=>setFacultyId(Number(e.target.value))}>{w.faculty.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Start<input required type="number" min={6.5} max={16.5} step={.5} value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>Duration (hours)<input required type="number" min={.5} max={10.5} step={.5} value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label></div>:mode==='plan'?<><div className="form-grid"><label>First date<input required type="date" value={date} onChange={e=>{setDate(e.target.value);setPlan(null);}}/></label><label>Calendar days<input required type="number" min={1} max={30} value={days} onChange={e=>{setDays(Number(e.target.value));setPlan(null);}}/></label><label>Exam duration<input required type="number" min={.5} max={4} step={.5} value={duration} onChange={e=>{setDuration(Number(e.target.value));setPlan(null);}}/></label></div><label>Modules ({modules.length} selected)<select multiple size={8} value={modules.map(String)} onChange={e=>{setModules(Array.from(e.target.selectedOptions,x=>Number(x.value)));setPlan(null);}}>{w.modules.map(m=><option key={m.id} value={m.id}>{m.code} · {m.name}</option>)}</select></label><p className="fine-print">Use Ctrl/Cmd to select multiple modules. Existing exams are preserved. Saturdays are excluded.</p>{plan&&<><p>{plan.proposed.length} examinations fit · {plan.unscheduled.length} could not be allocated.</p><div className="plan-preview">{plan.proposed.map((r,i)=><p key={i}>{w.modules.find(m=>m.id===r.module_id)?.code} · {r.date} {time(r.start)} · {w.rooms.find(x=>x.id===r.room_id)?.name}</p>)}</div></>}</>:<><p>Find the smallest available venue with enough seats for each existing exam.</p>{venues&&<><p>{venues.changes.length} venue changes · {venues.unresolved.length} exams need manual review.</p>{venues.changes.map(c=><p key={c.id}>Exam {c.id}: {w.rooms.find(r=>r.id===c.before)?.name} → {w.rooms.find(r=>r.id===c.after)?.name}</p>)}</>}</>}
 <label>Reason<textarea required minLength={5} value={reason} onChange={e=>setReason(e.target.value)}/></label>{error&&<ErrorNotice message={error}/>}<div className="actions"><Button type="submit" disabled={busy||reason.trim().length<5||(mode==='plan'&&!modules.length)}>{busy?'Calculating…':mode==='edit'?'Save exam':'Preview plan'}</Button>{mode!=='edit'&&<Button type="button" variant="primary" disabled={busy||reason.trim().length<5||(mode==='plan'?(!plan||!!plan.unscheduled.length):(!venues||!!venues.unresolved.length||!venues.changes.length))} onClick={()=>void save(true)}>Save reviewed plan</Button>}</div></form></Modal>}
 </div>;
}
