import {useEffect,useState} from "react";
import {AreaChart,Area,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,Cell} from "recharts";
import {Download} from "lucide-react";
import {useApp} from "../context";
import {api,errorText} from "../api";
import {PageHeader,Panel,Button,Badge,Modal,ErrorNotice} from "../components/ui";
import {DAYS} from "../types";

export default function OperationsAnalytics(){
 const {workspace:w}=useApp();const [filter,setFilter]=useState("All"),[compare,setCompare]=useState(false),[history,setHistory]=useState<{revision:number;conflict_count:number;detected_at:string}[]>([]),[error,setError]=useState("");
 useEffect(()=>{void api.get('/analytics/conflict-history').then(r=>setHistory(r.data)).catch(e=>setError(errorText(e)));},[w?.revision]);
 if(!w)return null;
 const kinds=['Rooms','Labs','Halls'];
 const group=(r:typeof w.rooms[number])=>r.kind==='Lab'?'Labs':r.name.startsWith('LT-')?'Halls':'Rooms';
 const series=DAYS.map((day,d)=>{const row:Record<string,string|number>={day:day.slice(0,3)};for(const kind of kinds){const rooms=w.rooms.filter(r=>r.active&&group(r)===kind),ids=new Set(rooms.map(r=>r.id)),occupied=new Set(w.sessions.filter(s=>s.day===d&&ids.has(s.room_id)).flatMap(s=>Array.from({length:s.duration*2},(_,i)=>`${s.room_id}:${s.start+i/2}`)));row[kind]=Math.round(occupied.size/Math.max(1,rooms.length*21)*1000)/10;}return row;});
 const active=filter==='All'?kinds:[filter],values=series.map(row=>active.reduce((sum,k)=>sum+Number(row[k]),0)/active.length),average=values.reduce((a,b)=>a+b,0)/values.length,peak=Math.max(...values);
 const staff=w.faculty.map(f=>({name:f.name,hours:w.sessions.filter(s=>s.faculty_id===f.id).reduce((sum,s)=>sum+s.duration,0),target:f.max_hours})).filter(f=>f.hours>0).sort((a,b)=>b.hours-a.hours).slice(0,8);
 const pressure=DAYS.map((day,d)=>({day:day.slice(0,3),sessions:w.sessions.filter(s=>s.day===d&&s.size>s.capacity).length}));
 const colors=['#15abc4','#002d6d','#48ad91'];
 function exportReport(){const lines=[['Day',...kinds],...series.map(r=>[r.day,...kinds.map(k=>r[k])])].map(row=>row.join(',')).join('\n'),url=URL.createObjectURL(new Blob([lines],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='nexus-weekly-utilization.csv';a.click();URL.revokeObjectURL(url);}
 return <div className="recorded-analytics"><PageHeader eyebrow="INTELLIGENCE · ANALYTICS" title="Operations Analytics" subtitle="Utilization, conflict and capacity patterns across the planning week." actions={<><div className="segmented">{['All',...kinds].map(x=><button className={filter===x?'active':''} key={x} onClick={()=>setFilter(x)}>{x}</button>)}</div><Button onClick={()=>setCompare(true)}>Compare Days</Button><Button variant="primary" onClick={exportReport}><Download size={14}/>Export Report</Button></>}/>{error&&<ErrorNotice message={error}/>}
 <Panel className="analytics-overview"><div className="section-heading"><div><h2>Utilization across the week <Badge>6 days</Badge></h2><p>Distinct occupied room-hours as a share of the 06:30–17:00 planning day</p></div><span className="muted">Revision {w.revision}</span></div><div className="recorded-kpis four inset">{[['Avg utilization',`${average.toFixed(1)}%`],['Peak day',`${peak.toFixed(1)}%`],['Teaching hours',w.metrics.teaching_hours],['Conflict-free',`${w.metrics.conflict_free}%`]].map(([label,value])=><Panel key={label}><span className="eyebrow">{label}</span><strong>{value}</strong></Panel>)}</div><div className="chart"><ResponsiveContainer width="100%" height={300}><AreaChart data={series} margin={{left:0,right:24,top:16}}><CartesianGrid vertical={false} stroke="#e9eaed"/><XAxis dataKey="day" tick={{fontSize:11}}/><YAxis unit="%" domain={[0,'auto']} tick={{fontSize:11}}/><Tooltip/>{active.map(k=><Area key={k} type="monotone" dataKey={k} stroke={colors[kinds.indexOf(k)]} fill={colors[kinds.indexOf(k)]} fillOpacity={.13} strokeWidth={2} isAnimationActive={false}/>)}</AreaChart></ResponsiveContainer></div><div className="analytics-legend">{active.map(k=><span key={k} style={{color:colors[kinds.indexOf(k)]}}>— {k}</span>)}</div></Panel>
 <div className="analytics-details"><Panel><div className="section-heading"><div><h2>Conflict history</h2><p>Recorded workspace revisions</p></div><Badge>{history.length} snapshots</Badge></div><ResponsiveContainer width="100%" height={230}><AreaChart data={history} margin={{right:24,left:0}}><CartesianGrid vertical={false} stroke="#e9eaed"/><XAxis dataKey="revision" tick={{fontSize:10}}/><YAxis allowDecimals={false}/><Tooltip/><Area dataKey="conflict_count" name="Hard conflicts" stroke="#48ad91" fill="#48ad91" fillOpacity={.08} isAnimationActive={false}/></AreaChart></ResponsiveContainer></Panel><Panel><div className="section-heading"><div><h2>Faculty load distribution</h2><p>Scheduled weekly hours · busiest faculty</p></div></div><ResponsiveContainer width="100%" height={230}><BarChart data={staff} margin={{right:24,left:0}}><CartesianGrid vertical={false} stroke="#e9eaed"/><XAxis dataKey="name" tickFormatter={name=>name.split(' ').slice(-1)[0]} tick={{fontSize:9}}/><YAxis/><Tooltip/><Bar dataKey="hours" name="Teaching hours" isAnimationActive={false}>{staff.map(f=><Cell key={f.name} fill={f.hours>f.target?'#d58a41':'#15abc4'}/>)}</Bar></BarChart></ResponsiveContainer></Panel></div>
 <Panel className="capacity-pressure"><div className="section-heading"><div><h2>Capacity pressure by day</h2><p>Sessions where attendance exceeds assigned room capacity</p></div></div><ResponsiveContainer width="100%" height={200}><BarChart data={pressure} margin={{right:24,left:0}}><CartesianGrid vertical={false} stroke="#e9eaed"/><XAxis dataKey="day"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="sessions" fill="#9e2852" maxBarSize={48} isAnimationActive={false}/></BarChart></ResponsiveContainer></Panel>
 {compare&&<Modal title="Compare planning days" onClose={()=>setCompare(false)}><div className="modal-body"><table><thead><tr><th>Day</th>{kinds.map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{series.map(r=><tr key={r.day}><td>{r.day}</td>{kinds.map(k=><td key={k}>{r[k]}%</td>)}</tr>)}</tbody></table><p className="fine-print">Current recurring timetable. Room groups exclude labs and lecture halls; unavailable periods are included in this fixed-day planning denominator.</p></div></Modal>}
 </div>;
}
