import {useNavigate} from "react-router-dom";
import {ArrowRight,AlertTriangle,CheckCircle2,ChevronRight,CalendarRange} from "lucide-react";
import {useApp} from "../context";
import {PageHeader,Panel,Button,Badge,Meter,AskNexus} from "../components/ui";
import {DAYS,DAY_ORDER,DAY_START,DAY_END,time} from "../types";

export function ScoreRing({value,size=126,tone="navy",label="SCORE"}:{value:number;size?:number;tone?:string;label?:string}){
 const color=tone==="green"?"var(--green)":tone==="maroon"?"var(--maroon)":tone==="teal"?"var(--teal)":"var(--primary)";
 return <div className="score-ring" style={{width:size,height:size}}><svg viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="44" fill="none" stroke="var(--surface-inset)" strokeWidth="6"/><circle cx="50" cy="50" r="44" fill="none" stroke={color} strokeWidth="6" strokeLinecap="round" strokeDasharray={`${Math.max(0,Math.min(100,value))*2.765} 276.5`} transform="rotate(-90 50 50)"/></svg><div><strong>{Math.round(value)}{!label&&<small>%</small>}</strong>{label&&<span>{label}</span>}</div></div>;
}
export function Heatmap(){
 const {workspace:w}=useApp();if(!w)return null;
 const hours=Array.from({length:Math.ceil(DAY_END-DAY_START)},(_,i)=>DAY_START+i);
 const loads=hours.map(h=>DAY_ORDER.map(d=>new Set(w.sessions.filter(s=>s.day===d&&s.start<h+1&&s.start+s.duration>h).map(s=>s.room_id)).size));const peak=Math.max(1,...loads.flat());
 return <div className="reference-heatmap"><div className="heatmap-line"><span/>{DAY_ORDER.map(d=><span key={d}>{DAYS[d].slice(0,3)}</span>)}</div>{hours.map((h,hi)=><div className="heatmap-line" key={h}><span>{hi%2===0?time(h):""}</span>{loads[hi].map((count,d)=><div key={d} title={`${DAYS[DAY_ORDER[d]]} ${time(h)} · ${count} occupied rooms`} className={`heat-cell load-${count===0?0:Math.ceil(count/peak*4)}`}/>)}</div>)}<div className="heatmap-scale"><span>Low</span><i/><span>Peak</span></div><p className="chart-caption">Occupied rooms relative to the busiest hour</p></div>;
}
export default function Overview(){
 const {workspace:w,can}=useApp(),navigate=useNavigate();if(!w)return null;
 const m=w.metrics,issues=w.conflicts.slice(0,4),priorities=w.conflicts.filter((c,i,all)=>all.findIndex(x=>x.kind===c.kind)===i).slice(0,3);
 return <div className="command-center"><PageHeader eyebrow="ISLINGTON COLLEGE / ACADEMIC OPERATIONS" title="Academic Command Center" subtitle="Your schedule, the issues that matter, and the next decision." actions={<Button variant="primary" onClick={()=>navigate("/timetable")}>Open timetable<ChevronRight size={16}/></Button>}/>
 {w.sessions.some(s=>s.data_status?.includes("Demo"))&&<div className="data-banner"><strong>Reference-backed demo.</strong> Teacher names and routine details come from your sources. Cohort sizes are assumptions; one room allocation was intentionally disrupted to demonstrate conflict resolution.</div>}<div className="command-priority"><Panel className="command-health"><span className="eyebrow">01 / SCHEDULE HEALTH</span><div className="health-reading"><strong>{m.sessions?m.health:"—"}<small>{m.sessions?"%":""}</small></strong><Badge tone={!m.sessions?"neutral":m.conflicts?"orange":"green"}>{m.conflicts?<AlertTriangle size={13}/>:<CheckCircle2 size={13}/>} {!m.sessions?"Awaiting timetable":m.conflicts?"Needs attention":"All constraints satisfied"}</Badge></div><p>{m.sessions?`${m.sessions} teaching sessions checked against room, faculty, cohort, capacity and availability constraints.`:"College rooms and published curricula are ready. Add teaching assignments or load the documented prototype to begin."}</p><Meter value={m.health} tone={m.conflicts?"orange":"green"}/><div className="health-context"><span><CalendarRange size={14}/>Revision {w.revision}</span><span>{m.sessions} sessions · {w.rooms.length} rooms</span></div></Panel>
 <Panel className="command-issues"><div className="section-heading"><div><span className="eyebrow">02 / ACTIVE ISSUES</span><h2>{m.conflicts?`${m.conflicts} constraints need review`:m.sessions?"No active conflicts":"Teaching data needed"}</h2></div><Badge tone={m.conflicts?"maroon":"neutral"}>{m.conflicts} issues</Badge></div>{issues.length?<div className="command-issue-list">{issues.map(c=><button key={c.id} onClick={()=>navigate(`/timetable?session=${c.session_ids[0]}`)}><AlertTriangle size={16}/><span><strong>{c.code} · {c.kind}</strong><small>{c.detail}</small></span><ChevronRight size={16}/></button>)}</div>:<div className="command-clear"><CheckCircle2 size={22}/><p>{m.sessions?"The current timetable passes every hard constraint. You can test a room closure in What-If Simulator.":"Configure faculty, cohorts and module allocations before running the scheduler."}</p></div>}<div className="command-panel-footer"><Button variant="ghost" onClick={()=>navigate(m.sessions?"/timetable?conflicts=1":"/import")}>{m.sessions?"Review timetable":"Check data import"}<ArrowRight size={14}/></Button></div></Panel></div>
 <section className="command-recommendations"><div className="section-heading"><div><span className="eyebrow">03 / NEXUS RECOMMENDATIONS</span><h2>{priorities.length?"Next decisions":"Plan the next step"}</h2></div><AskNexus context={{label:"Current schedule health"}} label="Explore schedule context"/></div><div className="command-recommendation-list">{priorities.length?priorities.map(c=><div key={c.id}><span className="recommendation-marker"><AlertTriangle size={16}/></span><div><h3>Resolve {c.kind.toLowerCase()} for {c.code}</h3><p>{c.detail}</p><AskNexus context={{session_id:c.session_ids[0],label:c.code}} label="Explain and find alternatives"/></div></div>):<div><span className="recommendation-marker"><CheckCircle2 size={17}/></span><div><h3>{m.sessions?"Test disruption before it happens":"Connect the college inventory"}</h3><p>{m.sessions?"Simulate a room closure and review the solver’s proposed moves before applying anything.":`${w.programmes.length} programme paths and ${w.rooms.length} rooms are available. Assign teachers and cohorts to modules to create teaching sessions.`}</p><Button variant="ghost" onClick={()=>navigate(m.sessions?"/whatif":"/programmes")}>{m.sessions?"Open what-if simulator":"Explore programmes"}<ArrowRight size={14}/></Button></div></div>}</div>{can("Registrar")&&!!m.conflicts&&<Button onClick={()=>navigate("/optimization")}>Calculate a feasible alternative<ArrowRight size={14}/></Button>}</section>
 <section className="command-insights"><div className="section-heading"><div><span className="eyebrow">04 / OPERATIONAL INSIGHTS</span><h2>The wider campus picture</h2></div><Button variant="ghost" onClick={()=>navigate("/analytics")}>View analytics<ArrowRight size={14}/></Button></div><div className="command-insight-grid"><Panel className="operational-load"><div className="section-heading"><div><h2>Weekly room occupancy</h2><p>Sunday–Friday · teaching hours</p></div></div><Heatmap/></Panel><Panel className="operational-facts">{[["Room utilization",`${m.utilization}%`,"Occupied room-hours"],["Faculty within target",`${m.faculty_balance}%`,`${m.overloads} above weekly target`],["Teaching hours",m.teaching_hours,`${w.faculty.length} faculty configured`],["Conflict-free sessions",`${m.conflict_free}%`,"Pass all hard constraints"]].map(([label,value,note])=><div key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>)}</Panel></div></section></div>;
}
