import {useState} from "react";
import {LockKeyhole,Unlock,AlertTriangle,Move} from "lucide-react";
import {useApp} from "../context";
import {api,errorText} from "../api";
import {Button,Modal,ErrorNotice,AskNexus} from "../components/ui";
import {DAYS,TIME_SLOTS,time,type Session,type Conflict} from "../types";
export default function SessionDetail({session:s,target,onClose,onSaved}:{session:Session;target:{day:number;start:number;room_id?:number}|null;onClose:()=>void;onSaved:()=>Promise<void>}){const {workspace:w,can}=useApp();const [room,setRoom]=useState(target?.room_id??s.room_id),[day,setDay]=useState(target?.day??s.day),[start,setStart]=useState(target?.start??s.start),[reason,setReason]=useState(""),[preview,setPreview]=useState<{conflicts:Conflict[]}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");if(!w)return null;const issues=w.conflicts.filter(c=>c.session_ids.includes(s.id));async function submit(confirm:boolean){setBusy(true);setError("");try{const {data}=await api.post(`/timetable/${s.id}/move`,{room_id:room,day,start,reason,revision:w!.revision,confirm});if(confirm)await onSaved();else setPreview(data);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <Modal title={`${s.code} · Session details`} onClose={onClose}><div className="modal-body"><h2>{s.module}</h2><div className="detail-grid">{[["Faculty",s.faculty],["Cohort",s.cohort],["Room",s.room],["Capacity",`${s.size} students / ${s.capacity} seats`],["Time",`${DAYS[s.day]} ${time(s.start)}–${time(s.start+s.duration)}`],["Requirements",`${s.room_type} · ${s.resources.join(", ")}`]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>{issues.map(c=><div className="notice error" key={c.id}><AlertTriangle size={17}/><div><strong>{c.kind}</strong><p>{c.detail}</p></div></div>)}<AskNexus context={{session_id:s.id,label:`${s.code} · ${s.room}`}} label="Ask NEXUS about this session"/>{can("Registrar")&&<><hr/><h3><Move size={16}/>Manual adjustment</h3>{s.locked?<p>This session is locked. Unlock it before adjusting.</p>:<><div className="form-grid"><label>Room<select value={room} onChange={e=>{setRoom(Number(e.target.value));setPreview(null);}}>{w.rooms.map(r=><option value={r.id} key={r.id}>{r.name} · {r.capacity} seats</option>)}</select></label><label>Day<select value={day} onChange={e=>{setDay(Number(e.target.value));setPreview(null);}}>{DAYS.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></label><label>Start time<select value={start} onChange={e=>{setStart(Number(e.target.value));setPreview(null);}}>{TIME_SLOTS.filter(h=>h+s.duration<=17).map(h=><option value={h} key={h}>{time(h)}</option>)}</select></label></div></>}<label>Reason for change<textarea value={reason} onChange={e=>{setReason(e.target.value);setPreview(null);}} placeholder="Explain this operational decision (at least 5 characters)"/></label>{preview&&<div className={`notice ${preview.conflicts.length?"error":"success"}`}>{preview.conflicts.length?preview.conflicts.map(c=>c.detail).join("; "):"The proposed move passes all hard constraints for this session."}</div>}<div className="actions"><Button variant="danger" disabled={busy||s.locked} onClick={async()=>{if(!window.confirm(`Delete ${s.code} from the timetable?`))return;setBusy(true);try{await api.delete(`/timetable/${s.id}`,{data:{revision:w.revision}});await onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>Delete session</Button><Button disabled={busy||reason.trim().length<5} onClick={async()=>{setBusy(true);try{await api.post(`/timetable/${s.id}/lock`,{locked:!s.locked,reason,revision:w.revision});await onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}}>{s.locked?<Unlock size={14}/>:<LockKeyhole size={14}/>} {s.locked?"Unlock":"Lock"}</Button>{!s.locked&&<><Button disabled={busy||reason.trim().length<5} onClick={()=>void submit(false)}>Preview impact</Button><Button variant="primary" disabled={busy||!preview||preview.conflicts.length>0} onClick={()=>void submit(true)}>Confirm & publish</Button></>}</div></>}{error&&<ErrorNotice message={error}/>}</div></Modal>;
}
