import {useEffect,useState} from "react";
import {Mail,Send,Users} from "lucide-react";
import {useApp} from "../context";
import {api,errorText} from "../api";
import {Button,Empty,ErrorNotice,PageHeader,Panel} from "../components/ui";
import type {RecordData} from "../types";

export default function StudentMessages(){
 const {workspace,can,notify,user}=useApp(); const [students,setStudents]=useState<RecordData[]>([]),[mode,setMode]=useState<"cohort"|"students"|"custom">("cohort"),[cohort,setCohort]=useState(""),[selected,setSelected]=useState<number[]>([]),[custom,setCustom]=useState(""),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(can("RTE"))void api.get<RecordData[]>("/data/students").then(response=>setStudents(response.data)).catch(error=>setError(errorText(error)));},[user?.id]);
 if(!workspace||!can("RTE"))return <Empty title="RTE access required"/>;
 async function submit(){setBusy(true);setError("");try{const custom_recipients=custom.split(/[\n,;]/).map(value=>value.trim()).filter(Boolean),payload={cohort_id:mode==="cohort"?Number(cohort):undefined,student_ids:mode==="students"?selected:[],custom_recipients:mode==="custom"?custom_recipients:[],subject,body};const response=await api.post("/emails/recipients",payload);notify(`${response.data.prepared} email draft(s) prepared.`);setSubject("");setBody("");setSelected([]);setCustom("");}catch(error){setError(errorText(error));}finally{setBusy(false);}}
 const hasRecipients=mode==="cohort"?!!cohort:mode==="students"?!!selected.length:!!custom.trim();
 return <><PageHeader eyebrow="COMMUNICATIONS / STUDENTS" title="Student Messaging" subtitle="Prepare reviewed email drafts for cohorts, selected students, or any custom email address. Delivery remains controlled through the email outbox."/><Panel><div className="segmented"><button className={mode==="cohort"?"active":""} onClick={()=>setMode("cohort")}><Users size={15}/>Entire cohort</button><button className={mode==="students"?"active":""} onClick={()=>setMode("students")}><Mail size={15}/>Selected students</button><button className={mode==="custom"?"active":""} onClick={()=>setMode("custom")}><Mail size={15}/>Custom addresses</button></div>{mode==="cohort"?<label>Recipient cohort<select required value={cohort} onChange={event=>setCohort(event.target.value)}><option value="">Select cohort…</option>{workspace.cohorts.map(value=><option key={value.id} value={value.id}>{value.name} · {value.size} students</option>)}</select></label>:mode==="students"?<label>Select students<select multiple size={12} value={selected.map(String)} onChange={event=>setSelected(Array.from(event.target.selectedOptions,option=>Number(option.value)))}>{students.map(student=><option key={student.id} value={student.id}>{String(student.name)} · {String(student.code)}</option>)}</select></label>:<label>Custom email addresses<textarea rows={5} value={custom} onChange={event=>setCustom(event.target.value)} placeholder="name@example.com, another@example.com"/><small>Separate addresses with commas, semicolons, or new lines. Duplicate addresses create one draft.</small></label>}<label>Subject<input value={subject} onChange={event=>setSubject(event.target.value)} placeholder="Timetable update"/></label><label>Message<textarea rows={7} value={body} onChange={event=>setBody(event.target.value)} placeholder="Write the message for the selected recipients…"/></label>{error&&<ErrorNotice message={error}/>}<div className="actions"><Button variant="primary" disabled={busy||!subject||!body||!hasRecipients} onClick={()=>void submit()}><Send size={15}/>{busy?"Preparing…":"Prepare email drafts"}</Button></div></Panel></>;
}
