export type RecordData = Record<string, unknown> & { id: number };
export type User = {id:number;name:string;email:string;role:string;active:boolean};
export type Room = {id:number;name:string;display_name:string;building:string;capacity:number;pc_count:number;kind:string;equipment:string[];unavailable:string[];active:boolean;source:string};
export type Faculty = {id:number;name:string;code:string;department:string;max_hours:number;unavailable:string[]};
export type CurriculumEntry = {code:string|null;name:string;credits:number|null;year?:number;semester?:number;optional_group?:string|null};
export type Programme = {id:number;name:string;department:string;award:string;level:string;specialization:string;curriculum:CurriculumEntry[];source:string};
export type Cohort = {id:number;name:string;programme_id:number;size:number;level:number};
export type Module = {id:number;code:string;catalogue_code?:string;name:string;programme_id:number;faculty_id:number;cohort_id:number;credits:number;room_type:string;resources:string[]};
export type Session = {cohort_ids:number[];session_type:string;source:string;data_status:string;notes:string;id:number;module_id:number;room_id:number;day:number;start:number;duration:number;locked:boolean;state:string;code:string;module:string;faculty_id:number;faculty:string;cohort_id:number;cohort:string;size:number;room:string;capacity:number;room_type:string;resources:string[]};
export type Conflict = {id:string;kind:string;session_ids:number[];code:string;detail:string;severity:string};
export type Metrics = {health:number;conflicts:number;conflict_free:number;utilization:number;faculty_balance:number;overloads:number;sessions:number;teaching_hours:number};
export type Rule = {id:number;name:string;kind:string;weight:number};
export type Workspace = {rooms:Room[];faculty:Faculty[];programmes:Programme[];cohorts:Cohort[];modules:Module[];sessions:Session[];conflicts:Conflict[];metrics:Metrics;rules:Rule[];revision:number;demo:boolean};
export type Change = {id:number;code:string;before:{room:string;day:number;start:number};after:{room:string;day:number;start:number};reason:string};
export type Run = {id:number;status:string;kind:string;revision:number;before:Metrics;after:Metrics;changes:Change[];explanation:string;created_at:string;scenario:{room_id?:number;day?:number}};
export type Readiness = {ready:boolean;checks:{key:string;label:string;ready:boolean;detail:string}[]};
export type SolverStage = {stage:string;label:string;status:"running"|"complete"|"failed"};
export const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Sunday"];
export const DAY_ORDER=[5,0,1,2,3,4];
export const DAY_START=6.5;
export const DAY_END=17;
export const TIME_SLOTS=Array.from({length:(DAY_END-DAY_START)*2},(_,i)=>DAY_START+i/2);
export const time=(h:number)=>{const minutes=Math.round(h*60);return `${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;};
export const roleLabel=(role?:string)=>role==="Super Admin"?"Registrar":role||"";
